version: '3.9'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2-python3.11
  env_file:
    - .env
  user: '0:0'
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins

services:
  postgres:
    container_name: postgres-db
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M

  clickhouse:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server:24.3
    user: '101:101'
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9363:9363'
    environment:
      - CLICKHOUSE_DB=airflow
      - CLICKHOUSE_USER=airflow
      - CLICKHOUSE_PASSWORD=airflow
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

      - CLICKHOUSE_USER_GRAFANA=grafana
      - CLICKHOUSE_PASSWORD_GRAFANA=grafana

      - CLICKHOUSE_PROMETHEUS_PORT=9363
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./shared_data:/opt/shared_data
      - ./prometheus_port.xml:/etc/clickhouse-server/config.d/prometheus_port.xml

    mem_limit: 1g
    mem_reservation: 512m
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  grafana:
    container_name: grafana
    image: grafana/grafana:11.1.0
    user: '472:472'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana

    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.2
    depends_on:
      - clickhouse

    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    restart: unless-stopped

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: 'no'
    depends_on:
      - postgres
      - clickhouse

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1.2G
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 1G
    restart: always
    depends_on:
      - airflow-webserver

  dbt:
    build:
      context: ./dbt
    image: youtube-dbt
    container_name: dbt
    depends_on:
      - clickhouse
      - postgres
    environment:
      DBT_PROFILES_DIR: /usr/app
    volumes:
      - ./profiles.yml:/usr/app/profiles.yml
      - ./dbt/youtube_project:/usr/app/youtube_project
    working_dir: /usr/app/youtube_project
    tty: true

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    ports:
      - '9090:9090'

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - ./airflow/logs:/opt/airflow/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
volumes:
  clickhouse_data:
  postgres_data:
  shared_data:
  grafana_data:
  prometheus_data:
