{
 "title": "Daily uploads",
 "time": { "from": "2025-11-30T18:00:00.000Z", "to": "2025-12-30T18:00:00.000Z" },
 "panels": [
  {
   "type": "stat",
   "description": "Total videos across all channels for the selected period.",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(*) AS \"Total Videos\"\r\nFROM analytics.int_youtube_videos_clean\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total views across all channels for the selected period.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    sum(daily_views) AS \"Total Views\"\r\nFROM analytics.fact_youtube_daily_monitorings"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The average length of videos published during the selected period duration data.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    avg(duration_seconds) as \"Avg Video Duration\"\r\nFROM analytics.fact_video_sparks\r\nWHERE $__timeFilter(published_at)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Average percentage of likes and comments per 100 views for the selected period.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    avg(daily_engagement_rate_percent) AS \"Audience Activity\"\r\nFROM analytics.fact_youtube_daily_monitorings\r\nWHERE date >= $__fromTime AND date <= $__toTime"
    }
   ]
  },
  {
   "title": "Daily Video Uploads in Youtube",
   "type": "timeseries",
   "description": "Shows the total number of videos published per day.",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toDate(date) AS time,\r\n    new_videos,\r\n    daily_views\r\nFROM analytics.fact_youtube_daily_monitorings\r\nWHERE date >= $__fromTime AND date <= $__toTime\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Video Distribution by Category",
   "type": "piechart",
   "description": "Comparison of categories by video volume and total views.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    category_name AS \"Category\", \r\n    sum(total_views) AS \"Total Views\"\r\nFROM analytics.fact_youtube_categories\r\nGROUP BY category_name\r\nORDER BY \"Total Views\" DESC"
    }
   ]
  },
  {
   "title": "Viral Sparks: Top Performing Videos",
   "type": "table",
   "description": "List of videos with the highest Day 1 view counts. Includes engagement tiering and like percentages. Hashtag-only titles are filtered out.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    title AS \"Video Title\",\r\n    category_name AS \"Category\",\r\n    views_day_1 AS \"Views (Day 1)\",\r\n    like_percentage_day_1 AS \"Like %\",\r\n    popularity_tier_day_1 AS \"Tier\"\r\nFROM analytics.fact_video_sparks\r\nWHERE title NOT LIKE '#%'       \r\n  AND title != ''                   \r\n  AND length(title) > 5             \r\n  AND published_at >= $__fromTime \r\n  AND published_at <= $__toTime\r\nORDER BY views_day_1 DESC\r\nLIMIT 15"
    }
   ]
  }
 ]
}